# Generated by Django 4.2.13 on 2024-05-15 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=None, max_length=20)),
                ('name', models.CharField(default=None, max_length=125)),
                ('instruction', models.CharField(default=None, max_length=300)),
                ('description', models.CharField(default=None, max_length=300)),
                ('price', models.FloatField(default=None)),
                ('med_png', models.CharField(blank=True, default=None, max_length=125)),
                ('all_sold_num', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='MedSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=125)),
                ('phone_number', models.CharField(default=None, max_length=15)),
                ('email', models.CharField(default=None, max_length=125)),
                ('adress', models.CharField(default=None, max_length=300)),
                ('description', models.CharField(default=None, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_sold_num', models.FloatField(default=None)),
                ('type_of_medicine', models.CharField(default=None, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default=None, max_length=15)),
                ('user_age', models.IntegerField()),
                ('basket', models.ManyToManyField(default=None, null=True, related_name='medicines', to='webapp.medicine')),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_department', to='webapp.pharmacydepartment'),
        ),
    ]
