# Generated by Django 4.2.13 on 2024-05-15 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_alter_myuser_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='basket',
            field=models.ManyToManyField(blank=True, default=None, related_name='basket_medicines', to='webapp.medicine'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(default=None)),
                ('meds', models.ManyToManyField(blank=True, default=None, related_name='order_medicines', to='webapp.medicine')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='my_orders',
            field=models.ManyToManyField(blank=True, related_name='orders', to='webapp.order'),
        ),
    ]
