# Generated by Django 4.2.13 on 2024-05-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_myuser_basket_order_myuser_my_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacydepartment',
            name='description',
            field=models.CharField(default='No description', max_length=300),
        ),
    ]
