# Generated by Django 4.2.13 on 2024-05-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_pharmacydepartment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='med_png',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
