# Generated by Django 4.2.13 on 2024-05-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_medicine_med_png'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='med_png',
            field=models.ImageField(blank=True, default=None, upload_to='media/images/'),
        ),
    ]
