# Generated by Django 4.2.13 on 2024-05-19 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_medicine_med_png'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.medicine')),
            ],
        ),
        migrations.AlterField(
            model_name='myuser',
            name='basket',
            field=models.ManyToManyField(blank=True, default=None, related_name='basket_medicines', to='webapp.basketitem'),
        ),
    ]
