# Generated by Django 4.2.13 on 2024-05-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_basketitem_alter_myuser_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='meds',
            field=models.ManyToManyField(blank=True, default=None, related_name='order_medicines', to='webapp.basketitem'),
        ),
    ]
