# Generated by Django 4.2.13 on 2024-05-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_order_meds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_str', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='my_promocodes',
            field=models.ManyToManyField(blank=True, default=None, related_name='user_promocodes', to='webapp.promocode'),
        ),
    ]
