# Generated by Django 4.2.13 on 2024-05-19 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_order_pick_up_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickUpPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_point', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='pick_up_point',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point', to='webapp.pickuppoint'),
        ),
    ]
