# Generated by Django 4.2.13 on 2024-05-19 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_pickuppoint_alter_order_pick_up_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pick_up_point',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point', to='webapp.pickuppoint'),
        ),
    ]
