# Generated by Django 4.2.13 on 2024-05-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_alter_order_pick_up_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default=None, max_length=15)),
                ('email', models.CharField(default=None, max_length=125)),
                ('adress', models.CharField(default=None, max_length=300)),
                ('description', models.CharField(default=None, max_length=300)),
            ],
        ),
    ]
