# Generated by Django 4.2.13 on 2024-05-21 08:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0015_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 21, 8, 53, 0, 479911, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='medicine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.medicine'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='department',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_department', to='webapp.pharmacydepartment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pick_up_point',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point', to='webapp.pickuppoint'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderer', to=settings.AUTH_USER_MODEL),
        ),
    ]
