# Generated by Django 4.2.13 on 2024-05-21 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0019_order_date_created_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.medicine'),
        ),
        migrations.AlterField(
            model_name='news',
            name='med',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.medicine'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderer', to=settings.AUTH_USER_MODEL),
        ),
    ]
