# Generated by Django 4.2.13 on 2024-05-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_alter_basketitem_medicine_alter_news_med_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='new_message',
            new_name='news_message',
        ),
        migrations.RemoveField(
            model_name='news',
            name='med',
        ),
        migrations.AddField(
            model_name='news',
            name='news_png',
            field=models.ImageField(blank=True, default=None, upload_to='media/images/'),
        ),
    ]
