# Generated by Django 4.2.13 on 2024-05-21 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_rename_new_message_news_news_message_remove_news_med_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='department',
            field=models.OneToOneField(default='media/images/noimg.png', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_department', to='webapp.pharmacydepartment'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_message',
            field=models.CharField(default='media/images/noimg.png', max_length=300),
        ),
    ]
