# Generated by Django 4.2.13 on 2024-05-21 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_alter_medicine_department_alter_news_news_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='department',
            field=models.ForeignKey(default='media/images/noimg.png', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_department', to='webapp.pharmacydepartment'),
        ),
    ]
