# Generated by Django 4.2.13 on 2024-05-21 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_alter_medicine_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_department', to='webapp.pharmacydepartment'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='med_png',
            field=models.ImageField(blank=True, default='media/images/noimg.png', upload_to='media/images/'),
        ),
    ]
