# Generated by Django 4.2.13 on 2024-05-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_alter_medicine_department_alter_medicine_med_png'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='all_sold_num',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.CharField(default='Нет описания', max_length=300),
        ),
        migrations.AlterField(
            model_name='medsupplier',
            name='description',
            field=models.CharField(default='Нет описания', max_length=300),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_message',
            field=models.CharField(default='Содержание', max_length=300),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_png',
            field=models.ImageField(blank=True, default='media/images/noimg.png', upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='pharmacydepartment',
            name='all_sold_num',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pharmacydepartment',
            name='description',
            field=models.CharField(default='Нет описания', max_length=300),
        ),
    ]
