# Generated by Django 4.2.13 on 2024-05-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_alter_medicine_all_sold_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_png', models.ImageField(blank=True, default='media/images/plot.png', upload_to='media/images/')),
            ],
        ),
    ]
