# Generated by Django 4.2.13 on 2024-05-22 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0026_monthplot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default=None, max_length=15)),
                ('email', models.CharField(default=None, max_length=125)),
                ('emp_png', models.ImageField(blank=True, default='media/images/noimg.png', upload_to='media/images/')),
                ('job_title', models.CharField(default=None, max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Вакансия', max_length=300)),
                ('description', models.CharField(default='Ее описание', max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='medicine',
            name='code',
            field=models.CharField(default='Код продукта', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='instruction',
            field=models.CharField(default='Нет инструкции', max_length=300),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='pick_up_point',
            field=models.CharField(default='Точка самовывоза', max_length=100),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='promo_str',
            field=models.CharField(default='Промокод', max_length=20),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(default='Содержание', max_length=300)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewiew_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='faq',
            name='vacancies',
            field=models.ManyToManyField(blank=True, default=None, related_name='company_vacs', to='webapp.vacancy'),
        ),
    ]
