# Generated by Django 4.2.13 on 2024-05-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_employee_vacancy_alter_medicine_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='mark',
            field=models.FloatField(default=10),
        ),
    ]
