# Generated by Django 4.2.13 on 2024-05-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_review_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='all_sold_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='mark',
            field=models.IntegerField(default=10),
        ),
    ]
