# Generated by Django 4.2.13 on 2024-05-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_vacancy_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='f_name',
            field=models.CharField(default='Имя', max_length=300),
        ),
        migrations.AddField(
            model_name='employee',
            name='l_name',
            field=models.CharField(default='Фамилия', max_length=300),
        ),
    ]
