# Generated by Django 4.2.13 on 2024-05-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0032_alter_myuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='description',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.CharField(default='Нет описания', max_length=1000),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='instruction',
            field=models.CharField(default='Нет инструкции', max_length=1000),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_message',
            field=models.CharField(default='Содержание', max_length=1000),
        ),
        migrations.AlterField(
            model_name='pharmacydepartment',
            name='description',
            field=models.CharField(default='Нет описания', max_length=1000),
        ),
        migrations.AlterField(
            model_name='review',
            name='context',
            field=models.CharField(default='Содержание', max_length=1000),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.CharField(default='Ее описание', max_length=1000),
        ),
    ]
