# Generated by Django 4.2.13 on 2024-05-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0033_alter_faq_description_alter_medicine_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.CharField(default='Ее описание', max_length=3000),
        ),
    ]
