# Generated by Django 4.2.13 on 2024-05-24 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0036_alter_faq_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 24, 18, 44, 27, 2869, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monthplot',
            name='plot_png',
            field=models.ImageField(blank=True, default='D:/django/LabaDjWeb/media/images/plot.png', upload_to='media/images/'),
        ),
    ]
