# Generated by Django 4.2.13 on 2024-05-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0037_news_date_created_alter_monthplot_plot_png'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medsupplier',
            name='phone_number',
            field=models.CharField(default=None, max_length=13),
        ),
    ]
